### ISSUE TITLE
PUC Assign: Formaldehyde

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/ChemicalExposure-SSC#1016]
https://ccte-factotum.epa.gov/chemical/DTXSID7020637/

Assign PUCs to products with AU and No PUC assignment.

**Comment by mdmetcal** [comment]
I dropped this one because I think a lot of the products are very odd/technical and this would be done better with someone who has more experience assigning products/knows the PUC database better.

**Comment by cnlutz20** [comment]
remaining unassigned products provide too little information to assign to an appropriate puc
