### ISSUE TITLE
Finding New Data: Food Contact db Sources

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/ChemicalExposure-SSC#1033]
Review the Excel sheet provided, of supplementary data from the FCCdb: Food Contact Chemicals database.

These are all of the sources they used for the food contact db. 
This ticket is to investigate whether the original data sources are still available online, and if they are a good fit for inclusion into Factotum. 

For each source, record information on:

- Is the dataset available online? in english?
- What is the format of the data? Journal article, report, csv file, etc.
- What kind of information does it contain? (product info, ingredient lists, more generic lists of chemical, migration study?)
- How would it fit into Factotum (composition, chemical presence?)
- Does it contain chemicals we are interested in/have less data on (PFAS, pthalates, bisphenols?)

https://www.sciencedirect.com/science/article/pii/S0160412020321802

https://zenodo.org/record/4296944

https://www.foodpackagingforum.org/news/how-to-use-the-food-contact-chemicals-database-fccdb

**Comment by Sakshi-Handa** [comment]
[food_contact_db_sources.xlsx](https://github.com/HumanExposure/ChemicalExposure-SSC/files/12796295/food_contact_db_sources.xlsx)

**Comment by cnlutz20** [comment]
[food_contact_sources_notes(AutoRecovered).xlsx](https://github.com/HumanExposure/ChemicalExposure-SSC/files/13228328/food_contact_sources_notes.AutoRecovered.xlsx)
