### ISSUE TITLE
Clean up incorrect PUC assignments in Food and Drug PUC

### ISSUE THREAD

**Issue by kisaacs1** [HumanExposure/ChemicalExposure-SSC#1043]
Update PUC assignment for products from MALLINCKRODT SCIENCE PRODUCTS DIVISION that have been incorrectly assigned to "Food and Drug" PUC by batch assign, probably because the company is also a pharmaceutical company. Most of these should be "Raw Materials", I believe.  For example: https://ccte-factotum.epa.gov/product/497224/

**Comment by cnlutz20** [comment]
Should only the "science products division" MALLINCKRODT products be moved?
