### ISSUE TITLE
extract data for bell labs MSDS

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/ChemicalExposure-SSC#108]
Create an extracted text csv for the Bell Labs data group which is ready to load to Factotum.

1. Navigate to the Bell labs data group here: http://factotum.epa.gov/datagroup/63/

2. Download all pdf documents (so that you can process them)

3. Write a script to automatically extract the following fields from the SDS pdf documents
  - Date of issue (header)
  - Product Identifier (Section 1, do not worry about the 'TM' symbols)
  - Relevant identified uses (Section 1)
  - Component (Section 3; i.e. chemical name, some don't have anything but 'proprietary'; if so put proprietary as the chemical name; also include the inert and non-hazardous ingredients if listed)
  - CAS No. (Section 3; again some may just have proprietary)
  - % by Weight (Section 3)

4. Store extraction script on github (https://github.com/HumanExposure/data_mgmt_scripts) and ask Kathie to register in FActotum!

5. Select 'upload extracted text' on data group page in factotum, and then download the extracted text csv template. Complete the CSV template using the extracted data you have pulled from the .pdfs and 

In extracted text csv, columns should be filled in as follows:

* data_document_id (this is provided in the template for each filename)
* data_document_filename (as with above, the document ID and filename pairing provided in the template should be maintainted)
* prod_name ('product identifier' extracted above)
* doc_date ('date of issue' extracted above)
* rev_num (blank)
* raw_category ('Relevant identified uses')
* raw_cas (cas_number, be careful excel doesn't convert these to dates!!)
* raw_chem_name ('component', or chemical name)
* report_funcuse (blank)
* raw_min_comp (blank)
* raw_max_comp (blank)
* unit_type (this should be 3 for every record that has a number - if there are any chemicals listed that don't have a percentage listed,  you would put 2 for unit_type; not sure if this ever happens)
* ingredient_rank (blank)
* raw_central_comp (put the '% by weight' as you have extracted it above, e.g. '75-85' or '<10'

**Note**
The template provides one row for each filename. However, when the template is fully filled in and completed, there will be multiple rows for each file (one row for every chemical included in the file). For all fields that are not chemical dependent (e.g. prod_name, filename, etc) the value in that field will be repeated.

**Comment by larger-allison** [comment]
script in github: https://github.com/HumanExposure/data_mgmt_scripts/tree/master/Bell%20Labs%20Extraction
