### ISSUE TITLE
extract data for The Clorox Company data group MSDS

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/ChemicalExposure-SSC#109]
Create an extracted text csv and load to Factotum for the The Clorox Company data group.

1. Navigate to the The Clorox Company data group here: http://factotum.epa.gov/datagroup/171/

2. Download all pdf documents (so that you can process them)

3. Write a script to automatically extract the following fields from the MSDS pdf documents

Date prepared (footer)
Product Name (section I)
Description (section I)
Ingredient (including chemical name, CAS, and Concentration range) (Section III: Hazardous Ingredients)
*Note some MSDS appear to not have any chemicals listed in Section III

4. Store extraction script on github (https://github.com/HumanExposure/data_mgmt_scripts) and ask Kathie to register in Factotum!

5. Select 'upload extracted text' on data group page in factotum, and then download the extracted text csv template. Complete the CSV template using the extracted data you have pulled from the .pdfs.

In extracted text csv, columns should be filled in as follows:

data_document_id (this is provided in the template for each filename)
data_document_filename (as with above, the document ID and filename pairing provided in the template should be maintainted)
prod_name ('product name' extracted above)
doc_date ('date prepared' extracted above)
rev_num (blank)
raw_category ('Description' extracted above)
raw_cas (CAS extracted above, be careful excel doesn't convert these to dates!!)
raw_chem_name ('chemical name', extracted above)
report_funcuse (blank)
raw_min_comp (blank)
raw_max_comp (blank)
unit_type (this should be 3 for every record that has a number for weight fraction - if there are any chemical names listed that don't have an actual numeric percentage listed, you would put 2 for unit_type; not sure if this ever happens)
ingredient_rank (blank)
raw_central_comp (put the concentration range as you have extracted it above, e.g. '75-85' or '<10'

Note
The template downloaded from Factotum provides one row for each filename. However, when the template is fully filled in and completed, there will be multiple rows for each file (one row for every chemical included in the file). For all fields that are not chemical dependent (e.g. prod_name, filename, etc) the value in that field will be repeated.

6. Load to Factotum!

**Comment by larger-allison** [comment]
scripts in github: https://github.com/HumanExposure/data_mgmt_scripts/tree/master/The%20Clorox%20Company%201%20Extraction
