### ISSUE TITLE
QA: Airgas Hardgoods Generic 

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/ChemicalExposure-SSC#1092]
Ticket to QA the documents related to the extraction script [Airgas Hardgoods Generic Script].
This is a generic script used to extract some of the documents in the Airgas Hardgoods Group. https://ccte-factotum.epa.gov/datagroup/37/

https://ccte-factotum.epa.gov/qa/extractionscript/506/

Complete QA for all 102 documents in the group.

**Comment by cnlutz20** [comment]
There are a lot of documents with a lot of different composition values based on version of the product. Discussed with sakshi and we weren't sure if all of these should be extracted as components or not. 

Example
https://ccte-factotum.epa.gov/datadocument/181339/

**Comment by cnlutz20** [comment]
Per discussion at 5/16 factotum curation updates meeting, remaining multi product components were extracted with chemicals and cas numbers only, no composition.
