### ISSUE TITLE
PUC Assign: Chemours 

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/ChemicalExposure-SSC#1130]
There are two Chemours Groups:

Chemours SDS Non-US.  https://ccte-factotum.epa.gov/datagroup/922/

Chemours SDS https://ccte-factotum.epa.gov/datagroup/921/

This ticket is for PUC assignment. 
I think there are raw categories available, which can be used to assign many of the products.

**Comment by mdmetcal** [comment]
Need to reassign makeup pucs to new PUC for raw material makeup

**Comment by mdmetcal** [comment]
Changed the PUCS
