### ISSUE TITLE
Extraction: PFAS in Illinois Drinking Water

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/ChemicalExposure-SSC#1181]
https://epa.illinois.gov/topics/water-quality/pfas/pfas-statewide-investigation-network.html

Save the webpage as a PDF and extract this list of PFAS found in Illinois PFAS water supply sampling efforts. 

Add the list to the existing datasource for State of Illinois here. 
https://ccte-factotum.epa.gov/datasource/144/

Create a new datagroup for "PFAS in Drinking Water"

**Comment by mdmetcal** [comment]
Need to figure out issue with uploading data

**Comment by mdmetcal** [comment]
Uploads were bugged due to the excel file.
