### ISSUE TITLE
load extracted text data for CPDat/Walmart

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/ChemicalExposure-SSC#121]
For the [Walmart - in CPDat data group](http://factotum.epa.gov/datagroup/81/), complete extracted text file and load to Factotum. 

1. First, from dev_consumer_product, you will be pulling out the following pieces of data, only for data_sources_id="CMDID-0000230"

products table (can filter this table based on the data_sources_id identified above):
- products_id (i.e., the CMPID or unique identifier for each product)
- product_name
- manufacturer
- product_date

link the above to the 'ingredients' table using the products_id and pull the following from the ingredients table:
- fk_chemical_substances_id
- minimum_weight_fraction
- maximum_weight_fraction
- weight_fraction
- reported_functional_use

link the above to the 'chemical_substances' table using the fk_chemical_substances_id and pull the following from the chemical_substances table:
- cas
- name

*End result*
Should be a data set where you have linked, for every product in data_source_id= "CMDID-0000230",
(i.e. every unique CMPID), the product information (product name, manufacturer, etc), the ingredient information (weight fraction), and the chemical information (cas, chemical name)

2. You will then need to use the master_...._matchedfiles.csv located here: L:\Lab\HEM\Factotum\Data in Factotum\Walmart to identify the **filename** associated with each CMPID. In this master_...._matchedfiles.csv, there are filenames in columns H and I, and CMPIDs in column K. 
The tricky piece here is that some products have two identified filenames (hence columns H and I). We believe that, if a product has two identified filenames, that the files are actually identical and just exist as multiple copies with different filenames. But, we have only loaded one of the files into Factotum.

3. Then, for the data group identified at the beginning of the ticket, download the extracted text template from factotum, which includes filename. Using the data set you have created, and matching on filename, populate the extracted text template as follows:
- prod_name --> product name in your data set
- doc_date --> blank
- rev_num --> blank
- raw_category --> blank
- raw_cas --> cas from your data set
- raw_chem_name --> name/chemical name from your data set
- report_funcuse --> reported functional use from your data set (there may not be anything populated for this data set, I'm not sure)
- raw_min_comp --> minimum_weight_fraction from your data set
- raw_max_comp --> maximum_weight_fraction from your data set
- unit_type --> populated with '1'
- ingredient_rank --> blank
- raw_central_comp --> weight_fraction from your data set

Remember that in the populated extracted text template there will be multiple rows for every product, so any product-specific fields above will be repeated in those rows, and any chemical/ingredient specific fields above will have different data in each row for a product

4. Load the extracted data to Factotum! Associate extracted data with extraction script 'Walmart CPCPdb'

5. Add notes to the existing registered 'extraction script' here: https://github.com/HumanExposure/data_mgmt_scripts/blob/master/WalmartCPCPdb which include a brief description of the process (if it doesn't really differ from the above, you can link to this ticket itself and say 'process described in ticket #121 with a hyperlink to the ticket). WIthin the existing script registered in GitHub already you can also add any SQL query or similar that was used to pull the data out of dev_consumer_product, etc.)

**Comment by l-koval** [comment]
products_id CMPID-0116331 is not in master_CPCatWalmart_matchedfiles.csv

**Comment by kdionisio** [comment]
Data loaded but recognized there are many issues with previously extracted data. We will be going in to check/correct all previously extracted data for each data document.
