### ISSUE TITLE
QA of Siri group 2

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/ChemicalExposure-SSC#123]
Begin QA (http://factotum.epa.gov/qa/) for QA group 'Siri group 2' within Factotum. 

Note we will *not* be QAing all 22,000 documents. Please start working on QA and see how the documents are looking. Also note that you still are not able to save edits on the QA page so if a document needs edits just skip that document.

**Comment by kdionisio** [comment]
Edited to note that definition of done is completing 2-3% of the QA for the siri group 2.

**Comment by RKalsch** [comment]
Completed 3%. Skipped all that needed edits.
