### ISSUE TITLE
extract data for 3M data sources

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/ChemicalExposure-SSC#124]
Create an extracted text csv and load to Factotum for the 3M data source.

1. Navigate to the the 3M data source here: http://factotum.epa.gov/datasource/42. WIthin the 3M data source there are two data groups, however they appear to all have the same format MSDS. So, you should be able to write one script to extract data from both data groups.

2. Download all pdf documents from each data group (so that you can process them). You will want to process each data group separately so that you can upload the extracted text data for each data group separately.

3. Write a script to automatically extract the following fields from the MSDS pdf documents

Product name (Section 1)
Issue date (Section 1)
Product Use, Specific Use (Section 1)
Product Use, Intended Use (Section 1)
Ingredient (section 2)
CAS No (Section 2)
% by Wt (Section 2)

4. Store extraction script on github (https://github.com/HumanExposure/data_mgmt_scripts) and ask Kathie to register in Factotum!

5. Select 'upload extracted text' on data group page in factotum, and then download the extracted text csv template (you will need to do this separately for the two data groups). Complete the CSV template using the extracted data you have pulled from the .pdfs.

In extracted text csv, columns should be filled in as follows:

data_document_id (this is provided in the template for each filename)
data_document_filename (as with above, the document ID and filename pairing provided in the template should be maintainted)
prod_name ('product name' extracted above)
doc_date ('issue date' extracted above)
rev_num (blank)
raw_category (populate this with the 'specific use/intended use' extracted above)
raw_cas (CAS No. extracted above, be careful excel doesn't convert these to dates!!)
raw_chem_name ('ingredient', extracted above)
report_funcuse (blank)
raw_min_comp (blank)
raw_max_comp (blank)
unit_type (this should be 3 for every record that has a number or range for weight fraction - if there are any chemical names listed that don't have an actual numeric percentage listed, you would put 2 for unit_type; not sure if this ever happens)
ingredient_rank (blank)
raw_central_comp (populate with what you extracted from the '% by Wt' field in the MSDS)

Note
The template downloaded from Factotum provides one row for each filename. However, when the template is fully filled in and completed, there will be multiple rows for each file (one row for every chemical included in the file). For all fields that are not chemical dependent (e.g. prod_name, filename, etc) the value in that field will be repeated.

6. Load to Factotum!

**Comment by larger-allison** [comment]
LIST OF KITS
Automotive Division:
1365020, 1365094, 1365116
Industrial Adhesives and Tapes:
1363627, 1363636, 1363640, 1363654, 1363656, 1363683, 1363691, 1363702, 1363703, 1363704, 1363708, 1363709, 1363713, 1363714, 1363715, 1363716, 1363719, 1363725, 1363727, 1363731, 1363732, 1363733, 1363734, 1363735, 1363736, 1363737, 1363738, 1363739, 1363740, 1363742, 1363745, 1363749, 1363751, 1363754, 1363755, 1363756, 1363759, 1363760, 1363763, 1363766, 1363770, 1363784, 1363791, 1363795, 1363801, 1363804, 1363810, 1363814, 1363824, 1363825, 1363828, 1363835, 1363837, 1363840, 1363841, 1363844, 1363845, 1363847, 1363850, 1363851, 1363852, 1363854, 1364079, 1364147, 1364148, 1364149, 1364156, 1364161, 1364183, 1364194, 1364196, 1364200, 1364202, 1364203, 1364204, 1364220, 1364221, 1364223, 1364224, 1364299
Industrial Minerals:
None
Occupational Health and Safety:
1360100, 1360206, 1360207, 1360389, 1360390

**Comment by larger-allison** [comment]
script in github: https://github.com/HumanExposure/data_mgmt_scripts/tree/master/3M%20Extraction
