### ISSUE TITLE
upload extracted text for P&G Ing Disclosures

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/ChemicalExposure-SSC#149]
Upload extracted text for P&G Ingredient disclosures.

Working in this data group: http://factotum.epa.gov/datagroup/199/

1. Download extracted text template from data group page, to obtain the data document id to filename mapping

2. Extracted text file (Proctor Gamble Ing Disclosure Extracted Text.csv) is nearly complete, available here: L:\Lab\HEM\Factotum\Data in Factotum\Proctor and Gamble\pandg_ingredient_disclosures_kap_201507

3. To add/fill in on extracted text file referenced above:
- data document id (to match to filename)
- raw_min_comp ('predicted WF 05')
- raw_max_comp ('predicted WF 95')
- raw_central_comp ('predicted WF 50')

to obtain the raw comp/predicted WF values, pull from the comp_mod_predicted_weight_fractions_10042016.csv located here: L:\Lab\HEM\Factotum\Data in Factotum

To find the correct predicted weight fraction values for any given ingredient, match on reported_ingredient_count (i.e. total number of ingredients in the product) and ingredient_list_rank (rank of the ingredient in the list). 

4. When extracted text file is complete, upload to Factotum
- Extraction script: Proctor and Gamble (Ing Disclosures)
- Weight Fraction type: Predicted

**Comment by larger-allison** [comment]
222 out of 255 files were extracted
