### ISSUE TITLE
register and upload P&G SDS

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/ChemicalExposure-SSC#150]
Register records and upload documents for Proctor and Gamble SDS documents.

Create a new data group within this data source:  http://factotum.epa.gov/datasource/35

Documents to be registered are in this folder: L:\Lab\HEM\Factotum\Data in Factotum\Proctor and Gamble\Proctor and Gamble SDS Product Safety\P&G_MSDS_PDF

When creating the new data group, use the following:
 - Name: P&G SDS
 - Description: original CPDat data source (data_source.id=35); downloaded and extracted by ICF; see memo in supplemental document group
 - URL: https://pgproductsafety.com/productsafety/sds/
 - Group type: Composition
 - Downloaded by: kdionisi
 - Downloaded at: 7/15/2015
 - Download script: Proctor & Gamble SDS

- When completing the register records file, 
- document_type = SD
- url can be found in the P_G_URL_name_list.csv file located here: L:\Lab\HEM\Factotum\Data in Factotum\Proctor and Gamble\Proctor and Gamble SDS Product Safety OR the filename to URL mapping can be found in columns O and P of the Exposure_Data_P&G.xlsx file
**However, note that both the 'URL' file and the 'Exposure Data' file include _more_ files listed than we actually have physical files available - they include data on 2200-2400 urls/filenames and we only have ~1500 in the PDF folder. We only want to include those which we have an actual pdf for in the register records file.

2. Upload files to Factotum after data group is registered. 

**Another note, there seem to be some odd file characters (perhaps chinese characters?) in some filenames, so please check numbers when registering and uploading to make sure everything is getting captured.

**Comment by larger-allison** [comment]
1377 documents matched
