### ISSUE TITLE
clean up GP product records

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/ChemicalExposure-SSC#153]
For the Georgia Pacific data group (http://factotum.epa.gov/datagroup/20/)

- Check each document in the group to ensure that the document does not contain information for multiple products (e.g., like this: http://factotum.epa.gov/media/e02d9a20-dcde-46a4-ab9d-f35ab3ef2508/pdf/document_155284.pdf)
- if the document *does* contain information for multiple products, add a note indicating this on the data document page, AND add the document name to a comment in this ticket
- for each product in the GP data group, go to the product page, select the green 'edit' pencil in the upper right, and add any product specific information that is available on the pdf

**Comment by RKalsch** [comment]
-gp_61 has an error when I try to open it
-gp_62 has multiple products 
-gp_64 has multiple products 
-gp_65 has multiple products 
-gp_68 has an error when I try to open it
-gp_69 has multiple products
-gp_72 has multiple products 
-gp_73 has multiple products
-gp_74 has multiple products 
-gp_75 has multiple products
-gp_76 has multiple products 
-gp_78 has multiple products 
-gp_79 has multiple products 
-gp_82 has multiple products
-gp_83 has multiple products 
-gp_85 has multiple products 
-gp_86 has multiple products 
-gp_87 has multiple products 
-gp_88 has multiple products 
-gp_96 has multiple products 
-gp_12 has multiple products
-gp_121 has multiple products
-gp_122 has multiple products 
-gp_123 has multiple products 
-gp_13 has multiple products 
-gp_17 has multiple products 
-gp_18 has multiple products 
-gp_19 has multiple products 
-gp_20 has multiple products 
-gp_29 has multiple products 
-gp_30 has multiple products 
-gp_31 has multiple products 
-gp_32 has multiple products 
-gp_35 has multiple products 
-gp_36 has multiple products 
-gp_37 has multiple products 
-gp_38 has multiple products
-gp_39 has multiple products
-gp_40 has multiple products
-gp_0 has multiple products
-gp_101 has multiple products 
-gp_104 has multiple products 
-gp_111 has multiple products
-gp_118 has an error when I try to open it
-gp_119 has multiple products

**Comment by kdionisio** [comment]
need a ticket to resolve the documents which include multiple products
