### ISSUE TITLE
Actor data extraction (Arizona) - manual

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/ChemicalExposure-SSC#162]
Manually extract data from: http://factotum.epa.gov/datadocument/320435/

- open the pdf in a new window
- in the 'notes' section of the data document page, add 'extracted by: your initials' to the notes box (keep current notes also)
- From the data document page, select the green + sign to add extracted text.
- Fill out the web form with the below and save
    - Doc date: the date of the document (e.g. if a date exists on a report cover, or the publication date)
    - Cat code: ACToR_Assays_556
    - Description CPCat: pesticide active_ingredient
    - CPCat SourceType: ACToR Assays and Lists
    - Prod name: pesticides
    - Rev num: (blank)
    - CPCat Code: Arizona_PestUse_2005_AID_1
- Add extracted chemical data
    - extract chemical name/'active ingredient' and CAS listed in Table 3

**Comment by RKalsch** [comment]
I skipped the redundant chemicals in table 3.
