### ISSUE TITLE
actor data extraction (arizona) - script

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/ChemicalExposure-SSC#163]
Write a script to extract chemical data as follows for http://factotum.epa.gov/datadocument/320436/

Table 4 (page 21-23): Extract chemical name ('active ingredient') and CAS

Definition of Done:
1. Write script and load to Factotum. Ask Kathie to register!

2. From the [datagroup page](http://factotum.epa.gov/datagroup/90/), select 'Export all records in Arizona to csv.' In the document which is downloaded, identify the filename and ID (equivalent to data_document_id) for the document you are extracting by looking for the title.

Select 'upload extracted text' button on the [datagroup page](http://factotum.epa.gov/datagroup/90/) and download the extracted text csv template. 

3. Complete extracted text template *only for this document which you are extracting.* All data_document_ids and data_document_filenames for other documents can be ignored.

Fill in columns of extracted text template as follows and load to Factotum.
doc_date: 2007
raw_category: Pesticides: Active Ingredients
raw_cas: CAS from table
raw_chem_name: active ingredient from table
cat_code: ACToR_Assays_557
description_cpcat: pesticide active_ingredient
cpcat_code: Arizona_PestUse_2006_AID_1
cpcat_sourcetype: ACToR Assays and Lists

**Note it is ok to use the script to extract the chemical list (cas and chemical name) and then fill in the other fields manually if that is easier (or, code in the completion of the other fields into your script, but hard code in the values, e.g. code in to your script that for this source cat_code = ACToR_Assays_557)

**Comment by larger-allison** [comment]
script in github: https://github.com/HumanExposure/data_mgmt_scripts/tree/master/Arizona%202007%20Pesticides%20Annual%20Report

**Comment by larger-allison** [comment]
All Arizona scripts now here: https://github.com/HumanExposure/data_mgmt_scripts/tree/master/Arizona%20(Actor%20Extraction)
