### ISSUE TITLE
C&L Inventory 

### ISSUE THREAD

**Issue by RKalsch** [HumanExposure/ChemicalExposure-SSC#303]
Using this data source : http://factotum.epa.gov/datasource/56

Go to [this](https://echa.europa.eu/information-on-chemicals/cl-inventory-database) website to extract chemicals from C&L Inventory. There are 2,910 pages, but there is a link to download a csv of it at the bottom of the page.

**Comment by larger-allison** [comment]
Can't add 40,000 chemicals to one document
