### ISSUE TITLE
Actor QA - Europa Commission of Regulation (EC) No 1170/2009

### ISSUE THREAD

**Issue by larger-allison** [HumanExposure/ChemicalExposure-SSC#305]
http://factotum.epa.gov/qa/chemicalpresence/
Complete QA for Europa Commission of Regulation (EC) No 1170/2009

Note: This includes

- **Vitamins and minerals** which may be used in the **manufacture of food supplements** (page 2)
- Vitamin and mineral **substances** which may be used in the **manufacture of food supplements**  (page 3)
- Vitamin formulations and mineral **substances** which may be **added to foods** (page 6)

**Comment by RKalsch** [comment]
The names of the data documents don't match up. Not sure which ones I should QA.  Looking here: http://factotum.epa.gov/qa/chemicalpresencegroup/382/
