### ISSUE TITLE
ACToR Extraction: Statewide Endocrine Disrupting Compound Monitoring Study 2007-2008 - Report

### ISSUE THREAD

**Issue by l-koval** [HumanExposure/ChemicalExposure-SSC#350]
Extract tables 2, 3, 4, 5, 6, 7, 31, 32, 33, Appendix A- organic waste water compounds, Appendix A- Pharmaceuticals, Appendix A1, Appendix A2, Appendix B-water, Appendix B- sediment, MDA1, & MDA2 from *Statewide Endocrine Disrupting Compound Monitoring Study 2007-2008 - Report*: 

<http://factotum.epa.gov/media/047054df-34c1-4a19-b105-111bec675166/pdf/document_1371485.pdf>. 

You will need to save the report locally so you can create a new data group in the *ACToR CPCat Lists* data source. Follow the [SOP](https://github.com/HumanExposure/ChemicalExposure-SSC/wiki/SOP-for-Chemical-Presence-Extractions) starting at step 3. *Download Script* can remain blank.

Once all the text has been extracted and uploaded to the new data group, delete the original data document page found here: <http://factotum.epa.gov/datadocument/1371485/>

**ADDITIONAL NOTES**
- Tables 2 & 5- No limit of detection is explicitly stated, so we are not going to assume an inequality indicates that the chemical is below the limit of detection, though often this is the case. In other words, treat an inequality as a detect, but make a note on the data doc page that this is how we treated that particular case.
- Tables 31, 32, 33- No need to distinguish results from different water sources. If a chemical is detected in any of the sources, consider it detected.
- Tables MDA1 & MDA2- No need to distinguish results from different sites. If a chemical is detected at any site, considered it detected.

**Comment by larger-allison** [comment]
https://factotum.epa.gov/datagroup/702/
