### ISSUE TITLE
L drive space

### ISSUE THREAD

**Issue by larger-allison** [HumanExposure/ChemicalExposure-SSC#358]
I am beginning to run into errors where python won't let me save things on the L drive due to lack of space. I've gone and deleted things in my folder that I don't need anymore, but we'll probably run out again soon and I would rather not delete skin deep files until they've been QA'd just in case something happens and I have to re-upload. Can we get more space?

**Comment by kdionisio** [comment]
@larger-allison I pinged Kristin about this. She has put a lot of functional use data on the L drive but you are right we either need to get more space or get that functional use data off. Let me see if she responds tomorrow.

**Comment by kdionisio** [comment]
@larger-allison Kristin is actively deleting things now. If you still run into issues by this afternoon/tomorrow let me know.
