### ISSUE TITLE
List of non-consumer products chemical names

### ISSUE THREAD

**Issue by scott-8** [HumanExposure/ChemicalExposure-SSC#359]
Regarding what we talked about in our meeting about the PUC prediction model, can you provide me with a list of product names (or point me to where I can find it) where we wouldn't want them to be trained to a PUC? I've gotten the probabilities from the model but I need to figure out the thresholds/other metrics to disqualify products.

**Comment by kdionisio** [comment]
@scott-8 
See this data group (you should be able to pull these product names directly from the factotum database by subsetting on this data group): http://factotum.epa.gov/datagroup/47/

This is an example of a data group which has products, but where the products don't really fit into any of the PUCs that we have. The products therefore should not be assigned to a PUC with your model. This would be a good test to see, if you ran these product names through your prediction model, what happens?
