### ISSUE TITLE
Image issues when uploading product data

### ISSUE THREAD

**Issue by larger-allison** [HumanExposure/ChemicalExposure-SSC#366]
I played around with creating products for a small group of documents, and I'm having trouble uploading images. When I put the image url in the thumb_image or large_image columns, no image shows up on the product page. When I put the image url in the medium_image column, an image appears on the product page, but it is distorted. For example, this is a product page:
http://factotum.epa.gov/product/571354/
and this is the image I used:
https://www.crcindustries.com/products/media/catalog/product/cache/1/image/600x500/17f82f742ffe127f42dca9de82fb58b1/i/m/image_505600_1_20411_1_145019.jpg

**Comment by dmlyons2** [comment]
The difference in size is to ensure all images will render correctly on a page without distortion. On the product page we are using the medium image which should be an img 180px by 180px. The image you have uploaded is 154px by 466px which would push content down the page.  You will need to resize it to 180px by 180px. There are a ton of python packages that can help you with that, or websites, or apps. :)

I think this one can be closed.

**Comment by larger-allison** [comment]
the thumb_image and large_image options still do not work. Also, I was told that I should save the link to images instead of downloading them, but how am I supposed to resize an image with just a link?

**Comment by dmlyons2** [comment]
@larger-allison We would have to host the image. By saying the thumb and large image do not work do you mean they can not be uploaded?

We can force a resize in the browser - will discuss options with @kdionisio

**Comment by larger-allison** [comment]
correct, uploading the csv with the picture url in either the thumb or large image columns resulted in no images appearing on the product page
