### ISSUE TITLE
Chemical Presence - Vaginal Douches and Other Feminine Hygiene Products: Women's Practices and Perceptions of Product Safety

### ISSUE THREAD

**Issue by RKalsch** [HumanExposure/ChemicalExposure-SSC#390]
Vaginal douches and other feminine hygiene products: women's practices and perceptions of product safety. 

Link:  https://link.springer.com/article/10.1007%2Fs10995-005-0054-y

**Comment by l-koval** [comment]
No chemicals were mentioned in this report, neither in the text nor a table, so the report was not uploaded to Factotum. Was this intended as a Habits and Practices source?

**Comment by RKalsch** [comment]
Good catch! I'll make a note of this. Thank you!
