### ISSUE TITLE
Chemical Extraction - The Environmental Injustice of Beauty: Framing Chemical Exposures from Beauty Products as a Health Disparities Concern

### ISSUE THREAD

**Issue by RKalsch** [HumanExposure/ChemicalExposure-SSC#391]
The Environmental Injustice of Beauty: Framing Chemical Exposures from Beauty Products as a Health Disparities Concern 

Link: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5614862/

**Comment by larger-allison** [comment]
No chemicals tested
