### ISSUE TITLE
Error when editing CP group title

### ISSUE THREAD

**Issue by larger-allison** [HumanExposure/ChemicalExposure-SSC#393]
After creating a CP group (http://factotum.epa.gov/datagroup/583/), I realized the group title was cut off because it was too long. I tried editing the title by pressing the edit button in the top right corner of the group page, editing the name field, and pressing submit. When I did this, I got a message that the group type field is required, even though it is already set and can't be changed. Then, I tried to leave the form using the cancel button at the bottom, it did not work. Also, the header of the form says "Create New Data Group For Data Source "", even though I am editing the data group, not creating a new one, and the group name is not populated in between the quotation marks.

In summation:

- Factotum is not recognizing the group type field is filled out when editing a data group

- The cancel button no longer works after getting an error while editing a data group

- The header on the form for editing a data group is incorrect

![image](https://user-images.githubusercontent.com/45430904/68974563-132bb180-07bf-11ea-9c44-a48c1add58fe.png)

**Comment by l-koval** [comment]
This happened to me as well. I tried to change the group name for group 585 but was unable to save changes because it said the group type was not filled out even though it was. Additionally the cancel button does not work and I had to close the page and reopen it to get back to the data group.
