### ISSUE TITLE
Chemicals Extracted: McKiniey Resources, Inc

### ISSUE THREAD

**Issue by RKalsch** [HumanExposure/ChemicalExposure-SSC#436]
McKiniey Resources, Inc
Chemical Extraction: Textiles
[Link](https://www.mckinleyresources.com/raw-materials-alphabetical-order.html) If you click on the link it takes you to the CAS.

**Comment by larger-allison** [comment]
This supplier "supplies specialty chemicals & raw materials to cosmeceutical, nutraceutical, & HI&I manufacturers", it doesnt appear to be directly linked to the the textile industry
