### ISSUE TITLE
Method Ingredient Disclosures

### ISSUE THREAD

**Issue by larger-allison** [HumanExposure/ChemicalExposure-SSC#476]
https://methodhome.com/products/ 

## 1. Scrape Method website
Go to each product page and save:
- Product name
- Product image src
- Description (next to picture)
- Product page url
- Save ingredient disclosure pdf (get to this from the "CA ingredient disclosure requirements" button at the bottom of the product page)

Create source in Factotum for Method and create group for ingredient disclosures and register the documents that you downloaded

## 2. Extract Ingredient Disclosures
From each ingredient disclosure, extract: 
- Product name
- UPC
- Name of Company / Manufacturer
- Link to Safety Data Sheet
- Date of Disclosure
- Ingredient names
- Functions
- CAS numbers

Upload data to Factotum

## 3. Create products
Upload product data via csv following the product csv template
- title = product name (from step 1 or 2)
- upc = upc (from step 2)
- url = product page url (from step 1)
- short_description = description (from step 1)
- medium_image = product image src (from step 1)
- manufacturer = Name of Company / Manufacturer (from step 2)

**Comment by mhorton86** [comment]
not all pages have PDF:  https://methodhome.com/products/smarty-dish-dishwasher-tabs/

for these pages, should I extract composition from the page and print the page as a PDF for the documentation?
