### ISSUE TITLE
data extraction for Proctor & Gamble SDS - walmart

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/ChemicalExposure-SSC#48]
Write script to extract data from SDS sheets formatted by Proctor & Gamble. Data extracted should be saved to a .csv. Script will be applied to all Proctor & Gamble products in the Walmart MSDS data group.

Script can be written assuming that every SDS sheet will be in the same format. Linked below are example pdfs that can be used to write and test the script (can link to and then download/save the pdfs from each of the pages below for testing).

Script should be stored in this repository: https://github.com/HumanExposure/data_mgmt_scripts, where a folder can be created containing the script and a read me file. Along with the script, please store a readme.txt briefly describing your process, any nuances, etc; could include notes like 'In the output .csv file, 'prod' column is the Product Name as listed in Section 1 of the SDS'

Example scripts used on older Proctor & Gamble data sets are here: https://github.com/HumanExposure/data_mgmt_scripts/tree/master/ProctorGambleExtract
Unclear if the pdfs in this case were the same format as the set of pdfs which need to be extracted, however worth taking a look to see if some of this code can be reused.

Fields to extract from the pdf include:
Revision Date (Header)
Product Name (Section 1)
Product Identifier (Section 1)
Recommended use (may not be available on all SDS) (Section 1)
Manufacturer (Section 1, only need 1st line, do not need address)
Chemical name (Section 3)
Synonyms (Section 3)
CAS-No (Section 3)
Weight % (Section 3) (Note alongside numeric concentration we should also store a field 'units' where units = weight %)

http://factotum.epa.gov/datadocument/173983/
http://factotum.epa.gov/datadocument/268947/
http://factotum.epa.gov/datadocument/129197/
http://factotum.epa.gov/datadocument/128534/
http://factotum.epa.gov/datadocument/123571/
http://factotum.epa.gov/datadocument/143275/

**Comment by Akomandur** [comment]
Finished

**Comment by kdionisio** [comment]
script registered in factotum (P&G SDS - Walmart) and stored here https://github.com/HumanExposure/data_mgmt_scripts/tree/master/Proctor%20and%20Gamble%20Data%20Extraction_Feb2019
