### ISSUE TITLE
data extraction for Colgate-Palmolive

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/ChemicalExposure-SSC#49]
Write script to extract data from SDS sheets formatted by Colgate-Palmolive. Data extracted should be saved to a .csv. Script will be applied to all Colgate-Palmolive products in the Walmart MSDS data group.

Script can be written assuming that every SDS sheet will be in the same format. Linked below are example pdfs that can be used to write and test the script (can link to and then download/save the pdfs from each of the pages below for testing).

Script should be stored in this repository: https://github.com/HumanExposure/data_mgmt_scripts, where a folder can be created containing the script and a read me file. Along with the script, please store a readme.txt briefly describing your process, any nuances, etc; could include notes like 'In the output .csv file, 'prod' column is the Product Name as listed in Section 1 of the SDS'

Fields to extract from the pdf include:
Revision Date (Header)
Version (Header)
SDS Number (Header)
Product Name (Section 1)
Product code (Section 1)
Manufacturer (Section 1, only need 1st line, do not need address)
Recommended use (Section 1)
Chemical name (Section 3)
CAS-No (Section 3)
Concentration (% w/w) (Section 3) (Note alongside concentration we should also store a field 'units' where unit = % w/w

http://factotum.epa.gov/datadocument/161290/
http://factotum.epa.gov/datadocument/159993/
http://factotum.epa.gov/datadocument/159561/
http://factotum.epa.gov/datadocument/158199/
http://factotum.epa.gov/datadocument/159261/
http://factotum.epa.gov/datadocument/160952/

**Comment by larger-allison** [comment]
Script: https://github.com/HumanExposure/data_mgmt_scripts/tree/master/Colgate-Palmolive
