### ISSUE TITLE
data extraction for The Clorox Company SDS (for walmart)

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/ChemicalExposure-SSC#50]
Write script to extract data from SDS sheets formatted by The Clorox Company. Data extracted should be saved to a .csv. Script will be applied to all The Clorox Company products in the *Walmart* MSDS data group.

Script can be written assuming that every SDS sheet will be in the same format. Linked below are example pdfs that can be used to write and test the script (can link to and then download/save the pdfs from each of the pages below for testing).

Script should be stored in this repository: https://github.com/HumanExposure/data_mgmt_scripts, where a folder can be created containing the script and a read me file. Along with the script, please store a readme.txt briefly describing your process, any nuances, etc; could include notes like 'In the output .csv file, 'prod' column is the Product Name as listed in Section 1 of the SDS'

Fields to extract from the pdf include:
Issuing Date (Header)
Revision Date (Header)
Revision Number (Header)
Product Name (Section 1 - do not worry about the 'TM' etc. symbols)
EPA Registration Number (Section 1)
Recommended use (Section 1)
Chemical name (Section 3)
CAS No. (Section 3)
Weight % (Section 3) (Note alongside numeric concentration we should also store a field 'units' where units = weight %)

http://factotum.epa.gov/datadocument/143453/
http://factotum.epa.gov/datadocument/146471/
http://factotum.epa.gov/datadocument/141896/
http://factotum.epa.gov/datadocument/265617/
http://factotum.epa.gov/datadocument/125452/
http://factotum.epa.gov/datadocument/140984/

**Comment by l-koval** [comment]
script can be found at: [](https://github.com/HumanExposure/data_mgmt_scripts/tree/master/Clorox-Walmart)
