### ISSUE TITLE
Data extraction for Johnson & Johnson SDS

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/ChemicalExposure-SSC#51]
Write script to extract data from SDS sheets formatted by Johnson & Johnson. Data extracted should be saved to a .csv. Script will be applied to all Johnson & Johnson products in the Walmart MSDS data group.

**Note that for Johnson & Johnson, there are two slightly different SDS formats. Two separate scripts can be written for the two different formats if needed, however we would then also need a way to identify which pdfs are in which format, which may be difficult. Ideally we have one script that can extract data from both formats of the SDS.

 Linked below are example pdfs that can be used to write and test the script (can link to and then download/save the pdfs from each of the pages below for testing).

Script should be stored in this repository: https://github.com/HumanExposure/data_mgmt_scripts, where a folder can be created containing the script and a read me file. Along with the script, please store a readme.txt briefly describing your process, any nuances, etc; could include notes like 'In the output .csv file, 'prod' column is the Product Name as listed in Section 1 of the SDS'

Fields to extract from the pdf include:
Issue Date (Header)
Revision Date (Header, may only appear in some SDS)
Product Name (Section 1)
Safety Data Sheet Code (Section 1, only if easy since this is only in some of the SDS)
Specification No. (Section 1, only if easy since this is only in some of the SDS)
Recommended use (Section 1) - note the different format on diff. SDS (some have a PUC type phrase, some include a paragraph of disclaimers. really what we need is potentially everything before the first period (e.g. on this SDS we only need 'Personal Care Product')
Chemical name (Section 3)
CAS No. (Section 3)
Weight % (Section 3) (Note alongside numeric concentration we should also store a field 'units' where units = weight %)
**re. chemical name/CAS/weight %, note that for example this document includes a note instead of chemical name/cas/weight % - in this case ideally we would pull the note and 'Mixture' label (not sure if they are always labeled as Mixture in this case??)

http://factotum.epa.gov/datadocument/140001/
http://factotum.epa.gov/datadocument/175092/
http://factotum.epa.gov/datadocument/141720/
http://factotum.epa.gov/datadocument/128313/
http://factotum.epa.gov/datadocument/127779/
http://factotum.epa.gov/datadocument/123624/

**Comment by larger-allison** [comment]
Script in github: https://github.com/HumanExposure/data_mgmt_scripts/tree/master/Johnson%20and%20Johnson
