### ISSUE TITLE
QA - Detection of azo dyes and aromatic amines in women

### ISSUE THREAD

**Issue by larger-allison** [HumanExposure/ChemicalExposure-SSC#586]
https://factotum.epa.gov/qa/chemicalpresence/
QA Chemical Presence group: Detection of azo dyes and aromatic amines in women

**Don't need to QA this. Going to delete this CP document.** - Sakshi Handa

**Comment by Sakshi-Handa** [comment]
Thanks for reminding me of this. I deleted the data group/data document from the UI.
