### ISSUE TITLE
Extraction - EPA (Pesticide Residues)

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/ChemicalExposure-SSC#663]
https://factotum.epa.gov/datagroup/193/

1/6 documents not extracted. https://factotum.epa.gov/datadocument/1365243/

[Tolerances and Exemptions for Pesticide Chemical Residues in Food](https://ccte-factotum.epa.gov/datadocument/1365243/)

**wondering if we should make this its own Datagroup. 
because there are multiple tables that need to be extracted in Section D. 
That have different kinds of data, need to be tagged separately.** 

Can Extract chemicals by script from the Table of Contents
Section C - specific tolerances

Need to add a new datadocument for 
Section D - Exemptions from tolerances (pg 389)
Can extract chemicals, CAS and functional uses.

**Comment by cnlutz20** [comment]
New data group created for this document: 
Tolerances and Exemptions: Food Pesticide Residue] https://ccte-factotum.epa.gov/datagroup/925/
