### ISSUE TITLE
SOP for functional use curation

### ISSUE THREAD

**Issue by larger-allison** [HumanExposure/ChemicalExposure-SSC#696]

**Comment by Sakshi-Handa** [comment]
As of Tuesday Jan 10, 2023
The Standard Operating Procedure (SOP) for Curating Functional Use Data in Factotum [SOP I-SCDCD-DEQEB-SOP-4056-0/I-SCDCD-DEQEB-SOP-5010-0] has been approved, entered into QA Track, and is available for immediate use.
