### ISSUE TITLE
PUC Assign: Proctor and Gamble 

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/ChemicalExposure-SSC#753]
[Proctor & Gamble - Ingredient Disclosures](https://ccte-factotum.epa.gov/datagroup/199/)

 255 documents
approx 25 products need PUCs

[P&G SDS](https://ccte-factotum.epa.gov/datagroup/208/)

1377 documents
approx 75 need PUCs

**Comment by cnlutz20** [comment]
2 unknown products under Proctor & Gamble - Ingredient Disclosures
