### ISSUE TITLE
Extraction - Biocides in spray products

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/ChemicalExposure-SSC#780]
https://ccte-factotum.epa.gov/datagroup/446/

9 'documents' in factotum
Need to determine what tables are relevant for extraction.

**Comment by mhorton86** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/mhorton/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/mhorton/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">



rejected | reason
-- | --
Table 6.3 | Calibration information
Table 6.4 | LOD determination
Table 6.5 | Spiked compounds
Table 6.6 | Parameters of previously captured compound
Table 6.10 | Parameters of previously captured compound
Table 6.15 | Parameters of previously captured compound
Table 7.15 | No corresponding table found



</body>

</html>

**Comment by mhorton86** [comment]
Extract Table 7.3, include detected flags
