### ISSUE TITLE
Extraction - Exposure of children

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/ChemicalExposure-SSC#783]
https://ccte-factotum.epa.gov/datagroup/406/

Need to determine what tables to extract. There are documents for 25 tables, currently.

**Comment by cnlutz20** [comment]
https://github.com/HumanExposure/data_mgmt_scripts/blob/master/Danish%20CPS/children_exposure_script.Rmd

script is complete and uploaded into data management scripts

**Comment by cnlutz20** [comment]
Extra documents deleted and documents tagged with "(redo)" renamed to only have the name of the table
