### ISSUE TITLE
PUC Assign - Dichloromethane

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/ChemicalExposure-SSC#787]
https://ccte-factotum.epa.gov/chemical/DTXSID0020868/

approx 1500 unassigned PUCs
approx 550 auto assigned PUCs

Kristin guesses mostly lab supplies, paint strippers

**Comment by mhorton86** [comment]
Completed all auto assigned, partial completion of unassigned

**Comment by cnlutz20** [comment]
unassigned products reviewed, remaining ones have little product info to assign pucs
