### ISSUE TITLE
siri - register records and load data documents to factotum

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/ChemicalExposure-SSC#80]
Please register records and load all Siri data documents into Factotum continuing work from #79 .

A list of all Siri records is located in the file here:
L:\Lab\HEM\CPDat\Data to be entered into CPDat\Siri

And the original Siri files are located here:
L:\Lab\NCCT_ACToR\BUILD_2019Q1\data_collection_data\siri.org\DataPrep\msds\f1\siri.org\msds\f1

Siri data source already exists in Factotum: http://factotum.epa.gov/datasource/28

1. Save all siri data documents as .pdf (but maintain .html copies also)

2. Create a new data group for all siri products *which have an existing data document available*.
  - 'Create new data group' from the Siri page in FActotum
        Data group name: Siri CPCat data
        Description: Siri data included in original CPCat database and transferred to Factotum. Siri files were originally downloaded by  NCCT for the ACToR database.
        URL: https://hazard.com/
        Group type: composition
        Downloaded by: kdionisi
        Downloaded at: current date
        Download script: SIri
        Data source: SIRI
 
3. Complete registered records .csv and create the data group. Only include records for which a data document is available. Within the registered records.csv,
  - the 'filename' field should include the filename of the .pdf version of the original source files
  - the title field should be populated by the 'name' field in the siriall.csv file
  - the document_type field should be filled in as 2 for all records
  - the url field should be filled by the url field in the siriall.csv file
  - Note that in the register records file you will want to have only one row for every file you are trying to register (the siriall.csv file sometimes contains multiple rows per file due to multiple chemicals being associated with a single file)

4. In the newly created data group, upload all *PDF* data documents to 'match' them to the registered records. Note that each folder you select for uploading documents from must have <600 documents included in the folder.

**Comment by larger-allison** [comment]
some files are in L:\Lab\NCCT_ACToR\BUILD_2019Q1\data_collection_data\siri.org\DataPrep\msds\f2\siri.org\msds\f2

**Comment by kdionisio** [comment]
**Modifications to above ticket:
- Register documents into data groups in groups of 20-25,000 documents at a time (so multiple data groups will be needed). Attempt to group data docs within a data group by f1/f2 status and alphabetically
- Definition of Done will be registration of all documents into data groups. Upload of pdf documents will be done in a new/separate ticket.
