### ISSUE TITLE
WebScraping/Extraction: Tyco SDS

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/ChemicalExposure-SSC#808]
From the Tyco website, scrape all SDS documents, extract data and make product entries

- Extract 1 of each unique product name - looks like they have different languages, we want North American/American English :) 
- It asks for your name/email address once, but then you can download multiple SDS documents
- Extract the 'recommended use' for easy PUC assignment to fire extinguishing agent

https://tycosds.thewercs.com/external/private/search.aspx

**Comment by mhorton86** [comment]
Upload of documents and extracted text complete.  Creation of products on hold pending factotum updates.
