### ISSUE TITLE
create list of PUCS containing chemicals

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/ChemicalExposure-SSC#86]
Cross-walk list of 6 chemicals with composition file indicating chemicals in products from CPDat, and create a list of all PUCS which contain each of the 6 chemicals.

Composition file (NEW_composition_for_S2D.csv) available here:
ftp://newftp.epa.gov/exposure/HEM

6 chemicals of interest:
Limonene
138-86-3
DTXSID2029612

Methyl paraben
99-76-3
DTXSID4022529

Linalool
78-70-6
DTXSID7025502

Disodium EDTA (Ethylenediaminetetraacetic acid, disodium salt)
139-33-3
DTXSID9027073

Isopropanol
67-63-0
DTXSID7020762

1,2-Propylene glycol
57-55-6
DTXSID0021206

Definition of Done:
- For each of the 6 DTXSID's above, create a .csv listing all PUCS which include that DTXSID (in composition file, PUC is identified by the 'source.id' column)
- In the files for each chemical, along side the PUC/source.id, include columns that indicate the label for that PUC (see revisedPUCs_2017Mar28.xlsx in L:\Lab\HEM\CPDat\PUCs   -  in this file, the 'PUCID' matches the 'source.id' from the NEW_composition_... file, and the 'labels' for the PUC include the general_category, group, product_type and refined_product_type columns)

**Comment by l-koval** [comment]
files can be found in L:\Lab\HEM\PUCs Lists-Chemicals of Interest
