### ISSUE TITLE
Finding New Docs: DEA

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/ChemicalExposure-SSC#867]
For the DEA Data Source https://ccte-factotum.epa.gov/datasource/51/

Look for more recent (2020+) documents we can add, such as

NFLIS Drug Annual Report

**Comment by cnlutz20** [comment]
all reports can be found in the zip file below

[DEA.zip](https://github.com/HumanExposure/ChemicalExposure-SSC/files/13606035/DEA.zip)
