### ISSUE TITLE
PUC Assign: Gelest

### ISSUE THREAD

**Issue by cnlutz20** [HumanExposure/ChemicalExposure-SSC#907]
Data group: https://ccte-factotum.epa.gov/datagroup/951/

**Comment by Sakshi-Handa** [comment]
Assign PUCs to products in Gelest SDS.
Reopening ticket, it looks like the products haven't been assigned PUCs. 
Looks like most are 'chemical intermediates' according to raw category. 
would those go into 'raw materials'?
