### ISSUE TITLE
Download Combined List of Uncurated Chemicals

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/ChemicalExposure-SSC#908]
This ticket involves running the script to download uncurated chemicals from Factotum and generating a csv file.
https://ccte-factotum.epa.gov/chemical_curation/

Lets combine chemicals that are less than 2,500 records into one list. 
Leave out the large groups (Walmart-CPDat, 3M Spatial, Tyco, RB). We can send those lists separately.

**Comment by larger-allison** [comment]
[uncurated_chemicals_2023-03-08_12-45-09.csv](https://github.com/HumanExposure/ChemicalExposure-SSC/files/10923439/uncurated_chemicals_2023-03-08_12-45-09.csv)
