### ISSUE TITLE
PUC Assignment: Batteries

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/ChemicalExposure-SSC#942]
Assign Products from the high level Batteries PUC to the lower level batteries PUCs. 

https://ccte-factotum.epa.gov/puc/316/

Prioritize assignment to product batteries, i.e. laptop, car, watch batteries. 

Only assign to battery types, i.e. 'lithium', 'alkaline' if there is no other information on the battery.

**Comment by cnlutz20** [comment]
Reviewed most of products in gen cat Batteries puc to more specific pucs. Remaining products generally seem to be batteries but not enough info to assign them to more specific puc's.
