### ISSUE TITLE
PUC Assignment: Industrial Glass Cleaner

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/ChemicalExposure-SSC#950]
Add products to the new Industrial Glass Cleaner PUC. https://ccte-factotum.epa.gov/puc/464/

**Comment by cnlutz20** [comment]
Unassigning myself from this ticket.

This should be ongoing, I reviewed the general cleaning and general household cleaning pucs for industrial glass cleaners.

**Comment by Sakshi-Handa** [comment]
reviewed ticket. products were moved into the industrial glass cleaner PUC.
