### ISSUE TITLE
Functional Use Cleaning: Chemours

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/ChemicalExposure-SSC#972]
https://ccte-factotum.epa.gov/functional_use_curation/

Assign reported functional uses to harmonized categories for remaining uses.
See Excel sheet below for unassigned names that need to be mapped.

https://ccte-factotum.epa.gov/datagroup/921/

[Factotum_Chemours_SDS_raw_functional_use_records_20230522.xlsx](https://github.com/HumanExposure/ChemicalExposure-SSC/files/11533557/Factotum_Chemours_SDS_raw_functional_use_records_20230522.xlsx)

**Comment by cnlutz20** [comment]
most of these seem like product categorization, i.e. formulation, cosmetics, electronics etc. not functional uses per se. should these be removed?
